name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress"

permissions:
  contents: read

jobs:
  build:
    name: "Psalm ${{ matrix.psalm-version }}, PHP ${{ matrix.php-version }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4
          - 8.0
          - 8.1
        psalm-version:
          - 4
          - 5

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: composer

      - name: "Install dependencies for Psalm 4"
        if: "matrix.psalm-version == 4"
        run: "composer require ${{ env.COMPOSER_FLAGS }} vimeo/psalm:'4.x-dev' psalm/plugin-phpunit:dev-master"

      - name: "Install dependencies for Psalm 5"
        if: "matrix.psalm-version == 5"
        run: "composer require ${{ env.COMPOSER_FLAGS }} vimeo/psalm:'5.x-dev' psalm/plugin-phpunit:dev-master"

      - name: Run Tests
        run: vendor/bin/phpunit
